module.exports.studentController = require("./student.controller")
module.exports.adminController = require("./admin.controller")
module.exports.facultyController = require("./faculty.controller")
module.exports.schoolController = require("./school.controller")
module.exports.userController = require("./user.controller")